2021-08-22 20:28:21Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:28:21Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:28:21Z: StackExchange.Redis.RedisConnectionException: SocketClosed (ReadEndOfStream, 0-read, last-recv: 0) on dev-do-user-8817720-0.b.db.ondigitalocean.com:25061/Interactive, Idle/MarkProcessed, last: ECHO, origin: ReadFromPipe, outstanding: 9, last-read: 0s ago, last-write: 0s ago, unanswered-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 6 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.62.27853
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 20:28:21Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:28:21Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:28:21Z: StackExchange.Redis.RedisConnectionException: SocketClosed (ReadEndOfStream, 0-read, last-recv: 0) on dev-do-user-8817720-0.b.db.ondigitalocean.com:25061/Interactive, Idle/MarkProcessed, last: ECHO, origin: ReadFromPipe, outstanding: 9, last-read: 0s ago, last-write: 0s ago, unanswered-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 6 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.62.27853
   at StackExchange.Redis.TaskExtensions.TimeoutAfter(Task task, Int32 timeoutMs) in /_/src/StackExchange.Redis/TaskExtensions.cs:line 49
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 20:28:21Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:28:21Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:28:38Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:28:38Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:28:38Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:28:38Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:28:38Z: StackExchange.Redis.RedisConnectionException: SocketClosed (ReadEndOfStream, 0-read, last-recv: 0) on dev-do-user-8817720-0.b.db.ondigitalocean.com:25061/Interactive, Idle/MarkProcessed, last: ECHO, origin: ReadFromPipe, outstanding: 9, last-read: 0s ago, last-write: 0s ago, unanswered-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 9 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.62.27853
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 20:28:39Z: StackExchange.Redis.RedisConnectionException: SocketClosed (ReadEndOfStream, 0-read, last-recv: 0) on dev-do-user-8817720-0.b.db.ondigitalocean.com:25061/Interactive, Idle/MarkProcessed, last: ECHO, origin: ReadFromPipe, outstanding: 9, last-read: 0s ago, last-write: 0s ago, unanswered-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 9 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.62.27853
   at StackExchange.Redis.TaskExtensions.TimeoutAfter(Task task, Int32 timeoutMs) in /_/src/StackExchange.Redis/TaskExtensions.cs:line 49
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 20:28:39Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:28:39Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:28:44Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:28:44Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:28:49Z: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1164
2021-08-22 20:30:13Z: Database Started
2021-08-22 20:30:13Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:30:13Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:30:13Z: System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 59
2021-08-22 20:30:13Z: Pipelines.Sockets.Unofficial.ConnectionResetException: An existing connection was forcibly closed by the remote host.
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 59
   at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|10_0(SocketError e) in /_/src/Pipelines.Sockets.Unofficial/SocketAwaitableEventArgs.cs:line 87
   at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.GetResult() in /_/src/Pipelines.Sockets.Unofficial/SocketAwaitableEventArgs.cs:line 82
   at Pipelines.Sockets.Unofficial.SocketConnection.DoReceiveAsync() in /_/src/Pipelines.Sockets.Unofficial/SocketConnection.Receive.cs:line 64
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 20:30:13Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:30:13Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:30:13Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:30:13Z: StackExchange.Redis.RedisConnectionException: SocketClosed (ReadEndOfStream, 0-read, last-recv: 0) on dev-do-user-8817720-0.b.db.ondigitalocean.com:25061/Interactive, Idle/MarkProcessed, last: ECHO, origin: ReadFromPipe, outstanding: 9, last-read: 0s ago, last-write: 0s ago, unanswered-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 9 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.62.27853
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 20:30:13Z: StackExchange.Redis.RedisConnectionException: SocketClosed (ReadEndOfStream, 0-read, last-recv: 0) on dev-do-user-8817720-0.b.db.ondigitalocean.com:25061/Interactive, Idle/MarkProcessed, last: ECHO, origin: ReadFromPipe, outstanding: 9, last-read: 0s ago, last-write: 0s ago, unanswered-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 9 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.62.27853
   at StackExchange.Redis.TaskExtensions.TimeoutAfter(Task task, Int32 timeoutMs) in /_/src/StackExchange.Redis/TaskExtensions.cs:line 49
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 20:30:13Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:30:13Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:30:18Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:30:18Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:30:23Z: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1164
2021-08-22 20:31:21Z: Database Started
2021-08-22 20:31:21Z: System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 20:31:21Z: System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 20:31:21Z: System.Net.Sockets.SocketException (11001): No such host is known.
   at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 59
2021-08-22 20:31:21Z: System.Net.Sockets.SocketException (11001): No such host is known.
   at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 59
2021-08-22 20:31:21Z: System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 20:31:21Z: System.Net.Sockets.SocketException (11001): No such host is known.
   at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 59
2021-08-22 20:31:21Z: System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 20:31:21Z: System.Net.Sockets.SocketException (11001): No such host is known.
   at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 59
2021-08-22 20:31:21Z: System.Net.Sockets.SocketException (10057): A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
2021-08-22 20:31:21Z: System.Net.Sockets.SocketException (10057): A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
2021-08-22 20:31:21Z: System.Net.Sockets.SocketException (10057): A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
2021-08-22 20:31:21Z: System.Net.Sockets.SocketException (10057): A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
2021-08-22 20:31:26Z: System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 20:31:26Z: System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 20:31:26Z: System.Net.Sockets.SocketException (11001): No such host is known.
   at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 59
2021-08-22 20:31:26Z: System.Net.Sockets.SocketException (11001): No such host is known.
   at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 59
2021-08-22 20:31:26Z: System.Net.Sockets.SocketException (10057): A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
2021-08-22 20:31:26Z: System.Net.Sockets.SocketException (10057): A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
2021-08-22 20:31:26Z: StackExchange.Redis.RedisConnectionException: UnableToConnect on default:dznrqp8k5ywsgae3@dev-do-user-8817720-0.b.db.ondigitalocean.com:25061:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 5s ago, v: 2.2.62.27853
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 20:31:26Z: StackExchange.Redis.RedisConnectionException: UnableToConnect on default:dznrqp8k5ywsgae3@dev-do-user-8817720-0.b.db.ondigitalocean.com:25061:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 5s ago, v: 2.2.62.27853
   at StackExchange.Redis.TaskExtensions.TimeoutAfter(Task task, Int32 timeoutMs) in /_/src/StackExchange.Redis/TaskExtensions.cs:line 49
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 20:31:26Z: System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 20:31:26Z: System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 20:31:26Z: System.Net.Sockets.SocketException (11001): No such host is known.
   at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 59
2021-08-22 20:31:26Z: System.Net.Sockets.SocketException (11001): No such host is known.
   at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 59
2021-08-22 20:31:26Z: System.Net.Sockets.SocketException (10057): A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
2021-08-22 20:31:26Z: System.Net.Sockets.SocketException (10057): A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
2021-08-22 20:31:31Z: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1164
2021-08-22 20:37:30Z: Database Started
2021-08-22 20:37:30Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:37:30Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:37:30Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:37:30Z: StackExchange.Redis.RedisConnectionException: SocketClosed (ReadEndOfStream, 0-read, last-recv: 0) on dev-do-user-8817720-0.b.db.ondigitalocean.com:25061/Interactive, Idle/MarkProcessed, last: ECHO, origin: ReadFromPipe, outstanding: 10, last-read: 0s ago, last-write: 0s ago, unanswered-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 8 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.62.27853
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 20:37:30Z: System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 59
2021-08-22 20:37:30Z: StackExchange.Redis.RedisConnectionException: SocketClosed (ReadEndOfStream, 0-read, last-recv: 0) on dev-do-user-8817720-0.b.db.ondigitalocean.com:25061/Interactive, Idle/MarkProcessed, last: ECHO, origin: ReadFromPipe, outstanding: 10, last-read: 0s ago, last-write: 0s ago, unanswered-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 8 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.62.27853
   at StackExchange.Redis.TaskExtensions.TimeoutAfter(Task task, Int32 timeoutMs) in /_/src/StackExchange.Redis/TaskExtensions.cs:line 49
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 20:37:30Z: Pipelines.Sockets.Unofficial.ConnectionResetException: An existing connection was forcibly closed by the remote host.
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 59
   at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|10_0(SocketError e) in /_/src/Pipelines.Sockets.Unofficial/SocketAwaitableEventArgs.cs:line 87
   at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.GetResult() in /_/src/Pipelines.Sockets.Unofficial/SocketAwaitableEventArgs.cs:line 82
   at Pipelines.Sockets.Unofficial.SocketConnection.DoReceiveAsync() in /_/src/Pipelines.Sockets.Unofficial/SocketConnection.Receive.cs:line 64
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 20:37:30Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:37:30Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:37:30Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:37:30Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:37:35Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:37:35Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:37:40Z: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1164
2021-08-22 20:56:02Z: Database Started
2021-08-22 20:56:02Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:56:02Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:56:02Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:56:02Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:56:02Z: StackExchange.Redis.RedisConnectionException: SocketClosed (ReadEndOfStream, 0-read, last-recv: 0) on dev-do-user-8817720-0.b.db.ondigitalocean.com:25061/Interactive, Idle/MarkProcessed, last: ECHO, origin: ReadFromPipe, outstanding: 10, last-read: 0s ago, last-write: 0s ago, unanswered-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 9 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.62.27853
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 20:56:02Z: StackExchange.Redis.RedisConnectionException: SocketClosed (ReadEndOfStream, 0-read, last-recv: 0) on dev-do-user-8817720-0.b.db.ondigitalocean.com:25061/Interactive, Idle/MarkProcessed, last: ECHO, origin: ReadFromPipe, outstanding: 10, last-read: 0s ago, last-write: 0s ago, unanswered-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 9 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.62.27853
   at StackExchange.Redis.TaskExtensions.TimeoutAfter(Task task, Int32 timeoutMs) in /_/src/StackExchange.Redis/TaskExtensions.cs:line 49
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 20:56:02Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:56:02Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:56:07Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:56:07Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:56:12Z: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1164
2021-08-22 20:58:59Z: Database Started
2021-08-22 20:59:00Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:59:00Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:59:00Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:59:00Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:59:00Z: StackExchange.Redis.RedisConnectionException: SocketClosed (ReadEndOfStream, 0-read, last-recv: 0) on dev-do-user-8817720-0.b.db.ondigitalocean.com:25061/Interactive, Idle/MarkProcessed, last: ECHO, origin: ReadFromPipe, outstanding: 10, last-read: 0s ago, last-write: 0s ago, unanswered-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 9 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.62.27853
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 20:59:00Z: StackExchange.Redis.RedisConnectionException: SocketClosed (ReadEndOfStream, 0-read, last-recv: 0) on dev-do-user-8817720-0.b.db.ondigitalocean.com:25061/Interactive, Idle/MarkProcessed, last: ECHO, origin: ReadFromPipe, outstanding: 10, last-read: 0s ago, last-write: 0s ago, unanswered-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 9 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.62.27853
   at StackExchange.Redis.TaskExtensions.TimeoutAfter(Task task, Int32 timeoutMs) in /_/src/StackExchange.Redis/TaskExtensions.cs:line 49
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 20:59:00Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:59:00Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:59:05Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:59:05Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 20:59:10Z: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1164
2021-08-22 21:02:12Z: Database Started
2021-08-22 21:02:12Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 21:02:12Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 21:02:12Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 21:02:12Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 21:02:12Z: StackExchange.Redis.RedisConnectionException: SocketClosed (ReadEndOfStream, 0-read, last-recv: 0) on dev-do-user-8817720-0.b.db.ondigitalocean.com:25061/Interactive, Idle/MarkProcessed, last: ECHO, origin: ReadFromPipe, outstanding: 10, last-read: 0s ago, last-write: 0s ago, unanswered-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 9 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.62.27853
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 21:02:12Z: StackExchange.Redis.RedisConnectionException: SocketClosed (ReadEndOfStream, 0-read, last-recv: 0) on dev-do-user-8817720-0.b.db.ondigitalocean.com:25061/Interactive, Idle/MarkProcessed, last: ECHO, origin: ReadFromPipe, outstanding: 10, last-read: 0s ago, last-write: 0s ago, unanswered-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 9 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.62.27853
   at StackExchange.Redis.TaskExtensions.TimeoutAfter(Task task, Int32 timeoutMs) in /_/src/StackExchange.Redis/TaskExtensions.cs:line 49
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 21:02:12Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 21:02:12Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 21:02:18Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 21:02:18Z: System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 59
2021-08-22 21:02:18Z: Pipelines.Sockets.Unofficial.ConnectionResetException: An existing connection was forcibly closed by the remote host.
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 59
   at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|10_0(SocketError e) in /_/src/Pipelines.Sockets.Unofficial/SocketAwaitableEventArgs.cs:line 87
   at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.GetResult() in /_/src/Pipelines.Sockets.Unofficial/SocketAwaitableEventArgs.cs:line 82
   at Pipelines.Sockets.Unofficial.SocketConnection.DoReceiveAsync() in /_/src/Pipelines.Sockets.Unofficial/SocketConnection.Receive.cs:line 64
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-08-22 21:02:18Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 21:02:18Z: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
2021-08-22 21:02:22Z: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1164
2021-08-22 21:03:00Z: Database Started
2021-08-22 21:42:32Z: System.Net.HttpListenerException (5): Access is denied.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
2021-08-22 21:42:32Z: System.Net.HttpListenerException (5): Access is denied.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
2021-08-22 21:42:32Z: System.Net.HttpListenerException (5): Access is denied.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
2021-08-22 21:44:19Z: Database Started
2021-08-23 00:45:58Z: System.Net.HttpListenerException (5): Access is denied.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
2021-08-23 00:45:58Z: System.Net.HttpListenerException (5): Access is denied.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
2021-08-23 00:45:58Z: System.Net.HttpListenerException (5): Access is denied.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
2021-08-23 00:46:56Z: System.Net.HttpListenerException (5): Access is denied.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
2021-08-23 00:46:56Z: System.Net.HttpListenerException (5): Access is denied.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
2021-08-23 00:46:56Z: System.Net.HttpListenerException (5): Access is denied.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
2021-08-23 00:48:54Z: System.Net.HttpListenerException (5): Access is denied.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
2021-08-23 00:48:54Z: System.Net.HttpListenerException (5): Access is denied.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
2021-08-23 00:48:54Z: System.Net.HttpListenerException (5): Access is denied.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
2021-08-23 00:59:01Z: Database Started
2021-08-23 01:09:26Z: Database Started
2021-08-23 01:10:06Z: Database Started
2021-08-23 01:14:08Z: Database Started
2021-08-23 01:15:01Z: Database Started
2021-08-23 01:15:05Z: Hi
2021-08-23 01:15:05Z: Hi
2021-08-23 01:15:05Z: Database Request
2021-08-23 01:15:05Z: Database Request
2021-08-23 01:15:06Z: Get Request
2021-08-23 01:15:06Z: Set Request
2021-08-23 01:17:09Z: Database Started
2021-08-23 01:17:14Z: Database Request
2021-08-23 01:17:14Z: Set Request
2021-08-23 01:17:14Z: Database Request
2021-08-23 01:17:14Z: Get Request
2021-08-23 01:21:10Z: Database Started
2021-08-23 01:21:15Z: Database Request
2021-08-23 01:21:15Z: Set Request
2021-08-23 01:21:16Z: Database Request
2021-08-23 01:21:16Z: Get Request
2021-08-23 01:21:37Z: Database Request
2021-08-23 01:21:37Z: Set Request
2021-08-23 01:21:37Z: Database Request
2021-08-23 01:21:37Z: Get Request
2021-08-23 03:03:29Z: Database Started
2021-08-23 03:04:15Z: Database Request
2021-08-23 03:04:16Z: Set Request
2021-08-23 03:04:16Z: NewTest
2021-08-23 03:04:16Z: Database Request
2021-08-23 03:04:16Z: Get Request
2021-08-23 03:04:16Z: NewTest
2021-08-23 03:59:54Z: Database Started
2021-08-23 04:02:22Z: Database Request
2021-08-23 04:02:22Z: Get Request
2021-08-23 04:02:37Z: Database Request
2021-08-23 04:02:37Z: Set Request
2021-08-23 04:02:40Z: Database Request
2021-08-23 04:02:40Z: Set Request
2021-08-23 04:03:04Z: Database Request
2021-08-23 04:03:04Z: Get Request
2021-08-23 04:03:12Z: Database Request
2021-08-23 04:03:12Z: Set Request
2021-08-23 04:03:25Z: Database Request
2021-08-23 04:03:25Z: Set Request
2021-08-23 04:04:35Z: Database Request
2021-08-23 04:04:35Z: Get Request
2021-08-23 04:05:17Z: Database Request
2021-08-23 04:05:17Z: Get Request
2021-08-23 04:15:47Z: Database Request
2021-08-23 04:15:47Z: Get Request
2021-08-23 04:28:01Z: Database Started
2021-08-23 04:28:26Z: Database Request
2021-08-23 04:28:26Z: Get Request
2021-08-23 04:28:29Z: Database Request
2021-08-23 04:28:29Z: Set Request
2021-08-23 04:28:29Z: 4
2021-08-23 04:29:20Z: Database Started
2021-08-23 04:30:25Z: Database Request
2021-08-23 04:30:25Z: Get Request
2021-08-23 04:30:27Z: Database Request
2021-08-23 04:30:27Z: Set Request
2021-08-23 04:30:27Z: 4
2021-08-23 04:30:28Z: 4
2021-08-23 04:30:36Z: Database Request
2021-08-23 04:30:36Z: Set Request
2021-08-23 04:30:36Z: 3
2021-08-23 04:30:36Z: 3
2021-08-23 04:54:30Z: Database Started
2021-08-23 04:55:08Z: Database Request
2021-08-23 04:55:08Z: Get Request
2021-08-23 04:55:13Z: Database Request
2021-08-23 04:55:13Z: Set Request
